[package]
name = "distribd"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1.19", features = ["full"] }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "1.0.36"
data-encoding = "2.3.2"
ring = "0.16.20"
serde_json = "1.0.79"
uuid = { version = "1.1.2", features=["v4"] }
jwt-simple = "0.11.0"
regex = "1.5.6"
jsonschema = { version = "0.16", default-features = false }
log = "0.4.14"
urlencoding = "2.1.0"
chrono = {version = "0.4", features=["serde"]}
prometheus-client = "0.16.0"
figment = { version="0.10.6", features=["yaml"]}
platform-dirs = "0.3.0"
rand = "0.8.5"
serde_regex = "1.1.0"
jsonl = { version="4.0.1", features=["tokio"]}
anyhow = "1.0"
sled = "0.34.7"
raft = { version = "0.6.0" }
# Maybe remove this if we bump raft?  https://github.com/tikv/raft-rs/issues/463
protobuf = { version = "2", features = ["bytes"] }
clap = { version = "3.2.8", features=["derive"] }

[dev-dependencies]
reqwest-retry = "*" 
reqwest-middleware = "*"
lazy_static = "*"
simple-pool = "*"
tempfile = "*"
