[package]
name = "distribd"
version = "0.5.0"
readme = "README.md"
edition = "2021"
authors = [
    "John Carr <john.carr@unrouted.co.uk>",
]
description = "An OCI container image registry."
homepage = "https://github.com/distribd/distribd"
keywords = ["raft", "consensus"]
license = "Apache-2.0"
repository = "https://github.com/distribd/distribd"
publish = false

[[bin]]
name = "distribd"
path = "src/bin/main.rs"
bench = false

[dependencies]
openraft = { version="=0.9.13", features=["serde"]}
actix-web = { version="4.6.0", features=["rustls-0_23"]}
actix-files = "0.6.6"
async-trait = "0.1.80"
clap = { version = "4.5.7", features = ["derive", "env"] }
reqwest = { version = "0.12.5", default-features = false, features = ["json", "rustls-tls", "trust-dns"] }
tokio = { version = "1.39", default-features = false, features = ["sync"] }
tracing = "0.1.40"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
byteorder = "1.5.0"
serde = { version = "1.0.203", features = ["derive"] }
data-encoding = "2.6.0"
ring = "0.17.8"
serde_json = "1.0.117"
uuid = { version = "1.10.0", features=["v4"] }
jwt-simple = "0.12.9"
regex = "1.10.5"
jsonschema = { version = "0.18", default-features = false }
chrono = {version = "0.4", features=["serde"]}
prometheus-client = "0.22.2"
figment = { version="0.10.19", features=["yaml", "env"]}
platform-dirs = "0.3.0"
rand = "0.8.5"
serde_regex = "1.1.0"
anyhow = "1.0.86"
sled = "0.34.7"
bincode = "1.3.3"
futures-util = "0.3.30"
thiserror = "1.0.61"
reqwest-retry = "0.6.0"
reqwest-middleware = { version="0.3.1", features=["json"] }
sentry = { version="0.34.0", default-features=false, features=["backtrace", "contexts", "debug-images", "panic", "rustls"] }
sentry-actix = "0.34.0"
rustls = "0.23.9"
rustls-pemfile = "2.1.2"
notify = "6.1.1"
futures = "0.3"
x509-parser = "0.16.0"
actix-request-identifier = "4.2.0"
rustls-pki-types = { version = "1" }

[[bench]]
name = "manifest"
path = "benches/manifest.rs"
harness = false

[dev-dependencies]
maplit = "1.0.2"
tempfile = { version = "3.10.1" }
rstest = "0.21.0"
lazy_static = "1.5.0"
simple-pool = "0.0.17"
tracing-test = { version = "0.2.5", features = ["no-env-filter"] }
criterion = { version="0.5", features=["async_tokio"] }

[features]
docinclude = [] # Used only for activating `doc(include="...")` on nightly.

[package.metadata.docs.rs]
features = ["docinclude"] # Activate `docinclude` during docs.rs build.

[profile.release]
lto = "fat"
codegen-units = 1
