[package]
name = "distribd"
version = "0.4.0"
readme = "README.md"
edition = "2021"
authors = [
    "John Carr <john.carr@unrouted.co.uk>",
]
description = "An OCI container image registry."
homepage = "https://github.com/distribd/distribd"
keywords = ["raft", "consensus"]
license = "Apache-2.0"
repository = "https://github.com/distribd/distribd"
publish = false

[[bin]]
name = "distribd"
path = "src/bin/main.rs"
bench = false

[dependencies]
openraft = { version="=0.8.9", features=["serde"]}
actix-web = { version="4.3.1", features=["rustls"]}
actix-files = "0.6.2"
async-trait = "0.1.77"
clap = { version = "4.5.2", features = ["derive", "env"] }
reqwest = { version = "0.11.18", default-features = false, features = ["json", "rustls-tls", "trust-dns"] }
tokio = { version = "1.28", default-features = false, features = ["sync"] }
tracing = "0.1.38"
tracing-futures = "0.2.4"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
byteorder = "1.4.3"
serde = { version = "1.0.163", features = ["derive"] }
data-encoding = "2.4.0"
ring = "0.17.8"
serde_json = "1.0.96"
uuid = { version = "1.3.3", features=["v4"] }
jwt-simple = "0.12.9"
regex = "1.8.1"
jsonschema = { version = "0.17", default-features = false }
chrono = {version = "0.4", features=["serde"]}
prometheus-client = "0.22.1"
figment = { version="0.10.8", features=["yaml", "env"]}
platform-dirs = "0.3.0"
rand = "0.8.5"
serde_regex = "1.1.0"
anyhow = "1.0.80"
sled = "0.34.7"
bincode = "1.3.3"
futures-util = "0.3.28"
thiserror = "1.0.57"
reqwest-retry = "0.2.2"
reqwest-middleware = "0.2.2"
sentry = { version="0.32.2", default-features=false, features=["backtrace", "contexts", "debug-images", "panic", "rustls"] }
sentry-actix = "0.32.2"
# We don't want 0.21 until actix updates
rustls = "~0.20.8"
rustls-pemfile = "1.0.2"
notify = "6.0.0"
futures = "0.3"
x509-parser = "0.16.0"
actix-request-identifier = "4.1.0"

[[bench]]
name = "manifest"
path = "benches/manifest.rs"
harness = false

[dev-dependencies]
maplit = "1.0.2"
tempfile = { version = "3.10.1" }
rstest = "0.18.2"
lazy_static = "1.4.0"
simple-pool = "0.0.16"
tracing-test = { version = "0.2.4", features = ["no-env-filter"] }
criterion = { version="0.5", features=["async_tokio"] }

[features]
docinclude = [] # Used only for activating `doc(include="...")` on nightly.

[package.metadata.docs.rs]
features = ["docinclude"] # Activate `docinclude` during docs.rs build.

[profile.release]
lto = "fat"
codegen-units = 1
