[package]
name = "distribd"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
name = "distribd"
crate-type = ["cdylib"]

[profile.release]
lto = "thin"
overflow-checks = true

[dependencies]
pyo3 = "0.15.1"
pyo3-asyncio = { version = "0.15", features = ["tokio-runtime"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.4", features = ["full"] }
rocket = "0.5.0-rc.1"
serde = "*"
data-encoding = "*"
ring = "*"
serde_json = "*"
uuid = { version = "*", features=["v4"] }
jwt-simple = { git = "https://github.com/jedisct1/rust-jwt-simple" }
regex = "1.5.4"
jsonschema-valid = "0.4.0"
log = "0.4.14"

[build-dependencies]
pyo3-build-config = "*"
