raft:
    address: 0.0.0.0
    port: 8080

registry:
    address: 0.0.0.0
    port: 8000

token_server:
    enabled: false

    realm: http://localhost:5001/auth
    service: My registry
    issuer: My issuer
    public_key: token_server.pub


prometheus:
    address: 0.0.0.0
    port: 7080

storage: var

peers:
    - name: node1
      address: node1
      port: 8080

    - name: node2
      address: node2
      port: 8080

    - name: node3
      address: node3
      port: 8080
